spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: wanghaocun
  datasource:
    url: jdbc:mysql://vvv.wanghaocun.com:3306/dev
    username: root
    password: vvv.wanghaocun.com
  jpa:
    show-sql: true
  cache:
    redis:
      time-to-live: 3600000

